name: "Code Quality"

on:
  push:
    branches: [master]

  pull_request:
    branches: [master]

  workflow_dispatch:

jobs:
  test-analyze:
    runs-on: ubuntu-22.04
    container:
      image: "plugfox/flutter:3.10.5"
      options: --user root

    steps:
      - name: 🚂 Get latest code
        uses: actions/checkout@v3

      - name: 🚃 Cache pub modules
        uses: actions/cache@v3
        env: 
          cache-path: $PUB_CACHE
        with:
          path: ${{ env.cache-path }}
          key: ${{ runner.os }}-pubpackages-cache

      - name: 🐝 Dart tools activation
        run: |
          dart pub global activate coverage

      - name: 👷 Install Dependencies
        timeout-minutes: 1
        run: flutter pub get
      
      - name: 📦 Install dependencies in packages
        timeout-minutes: 1
        run: for package in packages/*; do (cd "$package" && flutter pub get); done

      - name: 😊 Run codegen
        run: dart run build_runner build --delete-conflicting-outputs

      - name: 🔎 Check format
        timeout-minutes: 1
        run: |
          dart format --set-exit-if-changed $(find lib test -name "*.dart" -not \( -name "*.*.dart" \) )

      - name: 📈 Check analyzer
        timeout-minutes: 1
        run: |
          flutter analyze --fatal-infos --fatal-warnings

      - name: 🧪 Run tests
        timeout-minutes: 2
        run: |
          flutter test --coverage -r expanded

      - name: 📥 Upload coverage to Codecov
        if: ${{ github.ref == 'refs/heads/main' }}
        timeout-minutes: 1
        uses: codecov/codecov-action@v3
